const Constants = {
    TOGGLE_SHOW_NEAREST_STORES: 'TOGGLE_SHOW_NEAREST_STORES', 
    TOGGLE_FULLSCREEN_MAP: 'TOGGLE_FULLSCREEN_MAP',
    CHANGE_SEARCH_TERM: 'CHANGE_SEARCH_TERM',
    CHANGE_MANUAL_SEARCH_OPTION: 'CHANGE_MANUAL_SEARCH_OPTION',
	SHOW_SUGGESTED_RESULTS: 'SHOW_SUGGESTED_RESULTS',
	HIDE_SUGGESTED_RESULTS: 'HIDE_SUGGESTED_RESULTS',
	SET_SELECTED_STORE: 'SET_SELECTED_STORE',
	SHOW_OFFLINE_MODAL: 'SHOW_OFFLINE_MODAL',
	DISMISS_OFFLINE_MODAL: 'DISMISS_OFFLINE_MODAL'
}

export default Constants
