const TOGGLE_SHOW_NEAREST_STORES = 'TOGGLE_SHOW_NEAREST_STORES'
const TOGGLE_FULLSCREEN_MAP = 'TOGGLE_FULLSCREEN_MAP'
const CHANGE_SEARCH_TERM = 'CHANGE_SEARCH_TERM'
const CHANGE_MANUAL_SEARCH_OPTION = 'CHANGE_MANUAL_SEARCH_OPTION'
const SHOW_SUGGESTED_RESULTS = 'SHOW_SUGGESTED_RESULTS'
const HIDE_SUGGESTED_RESULTS = 'HIDE_SUGGESTED_RESULTS'
const SET_SELECTED_STORE = 'SET_SELECTED_STORE'
const SHOW_OFFLINE_MODAL = 'SHOW_OFFLINE_MODAL'
const DISMISS_OFFLINE_MODAL = 'DISMISS_OFFLINE_MODAL'

const constants = {
    TOGGLE_SHOW_NEAREST_STORES, 
    TOGGLE_FULLSCREEN_MAP,
    CHANGE_SEARCH_TERM
}

export default constants
